cmake_minimum_required(VERSION 4.2)
project(Dx)

set(CMAKE_CXX_STANDARD 20)


add_executable(01 01.cpp)
add_executable(02 02.cpp)
add_executable(03 03.cpp)
add_executable(04 04.cpp)
add_executable(05 05.cpp)

add_executable(2-24-1-Tree T24A1-Tree.cpp)
add_executable(2-24-2-ArrSort T24A2-ArrSort.cpp)
add_executable(2-24-3-xAyB T24A3-xAyB.cpp)
add_executable(2-24-4-VectorJudge T24A4-VectorJudge.cpp)
add_executable(2-24-5-Student T24A5-Student.cpp)
add_executable(24-1 24-1.cpp)
add_executable(24-2 24-2.cpp)
add_executable(24-3 24-3.cpp)
add_executable(24-4 24-4.cpp)
add_executable(24-5 24-5.cpp)

add_executable(2-25-1-Matrix T25B1-Matrix.cpp)
add_executable(2-25-2-ArrSort T25B2-ArrSort.cpp)
add_executable(2-25-3-Terminal T25B3-Terminal.cpp)
add_executable(2-25-4-VectorStore T25B4-VectorStore.cpp)
add_executable(2-25-5-Shape T25B5-Shape.cpp)
add_executable(25-1 25-1.cpp)
add_executable(25-2 25-2.cpp)
add_executable(25-3 25-3.cpp)
add_executable(25-4 25-4.cpp)
add_executable(25-5 25-5.cpp)

add_executable(26-1-X 26A1-X.cpp)
add_executable(26-2-FindMax 26A2-FindMax.cpp)
add_executable(26-3-RemoveChar 26A3-RemoveChar.cpp)
add_executable(26-4-SplitNum 26A4-SplitNum.cpp)
add_executable(26-5-Employee 26A5-Employee.cpp)

add_executable(1-26B-1-Triangle T26B1-Triangle.cpp)
add_executable(1-26B-2-Password T26B2-Password.cpp)
add_executable(1-26B-3-TgSort T26B3-TgSort.cpp)
add_executable(1-26B-4-TrunS T26B4-TrunS.cpp)
add_executable(1-26B-5-Calculator T26B5-Calculator.cpp)

add_executable(0Template 0Template.cpp)