cmake_minimum_required(VERSION 4.2)
project(Dx)

set(CMAKE_CXX_STANDARD 20)


add_executable(2-24-1 T24A1-Tree.cpp)
add_executable(2-24-2 T24A2-ArrSort.cpp)
add_executable(2-24-3 T24A3-xAyB.cpp)
add_executable(2-24-4 T24A4-VetorJudge.cpp)
add_executable(2-24-5 T24A5-Student.cpp)
add_executable(24-1 24-1.cpp)
add_executable(24-2 24-2.cpp)
add_executable(24-3 24-3.cpp)
add_executable(24-4 24-4.cpp)
add_executable(24-5 24-5.cpp)

add_executable(2-25-1 T25B1-Matrix.cpp)
add_executable(2-25-2 T25B2-ArrSort.cpp)
add_executable(2-25-3 T25B3-Terminal.cpp)
add_executable(2-25-4 T25B4-VectorStore.cpp)
add_executable(2-25-5 T25B5-Shape.cpp)
add_executable(25-1 25-1.cpp)
add_executable(25-2 25-2.cpp)
add_executable(25-3 25-3.cpp)
add_executable(25-4 25-4.cpp)
add_executable(25-5 25-5.cpp)

add_executable(26-1 26A1-X.cpp)
add_executable(26-2 26A2-FindMax.cpp)
add_executable(26-3 26A3-RemoveChar.cpp)
add_executable(26-4 26A4-SplitNum.cpp)
add_executable(26-5 26A5-Employee.cpp)

add_executable(1-26B-1 T26B1-Triangle.cpp)
add_executable(1-26B-2 T26B2-Password.cpp)
add_executable(1-26B-3 T26B3-TgSort.cpp)
add_executable(1-26B-4 T26B4-TrunS.cpp)
add_executable(1-26B-5 T26B5-Calculator.cpp)

add_executable(0Template 0Template.cpp)