cmake_minimum_required(VERSION 4.2)
project(Dx)

set(CMAKE_CXX_STANDARD 20)

add_executable(1-26B-1 1-26B-1.cpp)
add_executable(1-26B-2 1-26B-2.cpp)
add_executable(1-26B-3 1-26B-3.cpp)
add_executable(1-26B-4 1-26B-4.cpp)
add_executable(1-26B-5 1-26B-5.cpp)
add_executable(2-24-1 2-24-1.cpp)
add_executable(2-24-2 2-24-2.cpp)
add_executable(2-24-3 2-24-3.cpp)
add_executable(2-24-4 2-24-4.cpp)
add_executable(2-24-5 2-24-5.cpp)
add_executable(2-25-1 2-25-1.cpp)
add_executable(2-25-2 2-25-2.cpp)
add_executable(2-25-3 2-25-3.cpp)
add_executable(2-25-4 2-25-4.cpp)
add_executable(2-25-5 2-25-5.cpp)
add_executable(24-1 24-1.cpp)
add_executable(24-2 24-2.cpp)
add_executable(24-3 24-3.cpp)
add_executable(24-4 24-4.cpp)
add_executable(24-5 24-5.cpp)
add_executable(25-1 25-1.cpp)
add_executable(25-2 25-2.cpp)
add_executable(25-3 25-3.cpp)
add_executable(25-4 25-4.cpp)
add_executable(25-5 25-5.cpp)
add_executable(26-1 26-1.cpp)
add_executable(26-2 26-2.cpp)
add_executable(26-3 26-3.cpp)
add_executable(26-4 26-4.cpp)
add_executable(26-5 26-5.cpp)
add_executable(0Template 0Template.cpp)